version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
   - './node_modules/**/*'
